### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by NowYouCanFindMe**

### CODE REVIEW

**Review by ccannon94 — APPROVED** [review]
Looks good! I like the new process

**Comment by ccannon94** [comment]
@NowYouCanFindMe you should be able to merge this now if you think it's ready

**Comment by NowYouCanFindMe** [comment]
Howdy Chris, can you merge the pull request?
It says, 'You're not authorized to merge this pull request'. A̶b̶o̶v̶e̶^̶^̶^̶
Edit, I mean below ↓↓↓

**Comment by NowYouCanFindMe** [comment]
Cools

**Pull request merged**
